# Generated by Django 3.2.6 on 2021-08-17 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloggerData',
            fields=[
                ('about', models.TextField()),
                ('designation', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('V', 'verified'), ('N', 'notVerified')], default='N', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
    ]
