# Generated by Django 3.2.6 on 2021-08-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggerdata',
            name='status',
            field=models.CharField(choices=[('verified', 'verified'), ('not verified', 'notVerified')], default='not verified', max_length=15),
        ),
    ]
