# Generated by Django 3.2.6 on 2021-08-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0005_auto_20210809_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbNail',
            field=models.ImageField(blank=True, default='1.png', upload_to=''),
        ),
    ]
