# Generated by Django 3.2.6 on 2021-08-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0006_alter_blog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbNail',
            field=models.ImageField(blank=True, default='1.jpg', upload_to=''),
        ),
    ]
